### ISSUE TITLE
Init - Feedback visuel

### ISSUE THREAD

**Issue by EtienneSchmitz** [poppy-project/ucia#33]
Ajouter un feedback le temps de l'initialisation du robot (dû majoritairement à l'initialisation de l'IA

Idée d'implémentation donné par les membres : 
- Faire clignoter la roue de DEL en mode horloge tournante 
- Jouer un son (Possibilité d'utilisation des sons préenregistré)

**Comment by davidjsherman** [comment]
Roue = DEL horloge tournant ?

**Comment by EtienneSchmitz** [comment]
Oui, j'ai mise à jour la description de l'issue pour être plus clair.

**Comment by davidjsherman** [comment]
```
var working = 0
var H[8] = [20,0,0,0,0,0,0,0]

onevent acc
if working != 0 then
	call leds.circle(H[0],H[1],H[2],H[3],H[4],H[5],H[6],H[7])
	H = [H[7],H[0],H[1],H[2],H[3],H[4],H[5],H[6]]
else
	call leds.circle(0,0,0,0,0,0,0,0)
end
```
